// Mocks generated by Mockito 5.4.5 from annotations
// in Equirent_Mobility/test/insurer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;
import 'dart:ui' as _i7;

import 'package:Equirent_Mobility/BLoC/auth/auth_context.dart' as _i6;
import 'package:Equirent_Mobility/services/API.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [APIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIService extends _i1.Mock implements _i2.APIService {
  MockAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get callOTPEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#callOTPEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#callOTPEndpoint),
            ),
          )
          as String);

  @override
  String get validateOTPEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#validateOTPEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#validateOTPEndpoint),
            ),
          )
          as String);

  @override
  String get loginEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#loginEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#loginEndpoint),
            ),
          )
          as String);

  @override
  String get callCitysEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#callCitysEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#callCitysEndpoint),
            ),
          )
          as String);

  @override
  String get createUserEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#createUserEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#createUserEndpoint),
            ),
          )
          as String);

  @override
  String get getCarsEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getCarsEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getCarsEndpoint),
            ),
          )
          as String);

  @override
  String get createVehicleEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#createVehicleEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#createVehicleEndpoint),
            ),
          )
          as String);

  @override
  String get getDocumentTypesEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getDocumentTypesEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getDocumentTypesEndpoint),
            ),
          )
          as String);

  @override
  String get getServicingListEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getServicingListEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getServicingListEndpoint),
            ),
          )
          as String);

  @override
  String get getTotalGuidesEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getTotalGuidesEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getTotalGuidesEndpoint),
            ),
          )
          as String);

  @override
  String get getAllGuidesEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getAllGuidesEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getAllGuidesEndpoint),
            ),
          )
          as String);

  @override
  String get getInsurersEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getInsurersEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getInsurersEndpoint),
            ),
          )
          as String);

  @override
  String get accountRecoveryEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#accountRecoveryEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#accountRecoveryEndpoint),
            ),
          )
          as String);

  @override
  String get validateResetOTPEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#validateResetOTPEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#validateResetOTPEndpoint),
            ),
          )
          as String);

  @override
  String get registerNotificationsEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#registerNotificationsEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#registerNotificationsEndpoint),
            ),
          )
          as String);

  @override
  String get getProfileEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#getProfileEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#getProfileEndpoint),
            ),
          )
          as String);

  @override
  String get queryHistoryEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#queryHistoryEndpoint),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#queryHistoryEndpoint),
            ),
          )
          as String);

  @override
  String getVehicleDetailEndpoint(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleDetailEndpoint, [id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleDetailEndpoint, [id]),
            ),
          )
          as String);

  @override
  String deleteVehicleEndpoint(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVehicleEndpoint, [id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deleteVehicleEndpoint, [id]),
            ),
          )
          as String);

  @override
  String getFileEndpoint(String? folderName, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFileEndpoint, [folderName, id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getFileEndpoint, [folderName, id]),
            ),
          )
          as String);

  @override
  String getVehicleExpirationEndpoint(int? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleExpirationEndpoint, [vehicleId]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleExpirationEndpoint, [vehicleId]),
            ),
          )
          as String);

  @override
  String getVehicleHistoryEndpoint(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleHistoryEndpoint, [plate]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleHistoryEndpoint, [plate]),
            ),
          )
          as String);

  @override
  String getVehicleFinesEndpoint(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleFinesEndpoint, [plate]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleFinesEndpoint, [plate]),
            ),
          )
          as String);

  @override
  String getVehicleFinesSimitEndpoint(String? search) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleFinesSimitEndpoint, [search]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleFinesSimitEndpoint, [search]),
            ),
          )
          as String);

  @override
  String getVehicleAccidentsEndpoint(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleAccidentsEndpoint, [plate]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleAccidentsEndpoint, [plate]),
            ),
          )
          as String);

  @override
  String getVehicleTransferHistoryEndpoint(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleTransferHistoryEndpoint, [plate]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehicleTransferHistoryEndpoint, [plate]),
            ),
          )
          as String);

  @override
  String getVehiclePrecautionaryMeasuresEndpoint(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getVehiclePrecautionaryMeasuresEndpoint, [
              plate,
            ]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getVehiclePrecautionaryMeasuresEndpoint, [
                plate,
              ]),
            ),
          )
          as String);

  @override
  String getSpecialAlertEndpoint(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecialAlertEndpoint, [id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getSpecialAlertEndpoint, [id]),
            ),
          )
          as String);

  @override
  String getDeleteAlertEndpoint(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeleteAlertEndpoint, [id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getDeleteAlertEndpoint, [id]),
            ),
          )
          as String);

  @override
  String updateExpirationEndpoint(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpirationEndpoint, [id]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#updateExpirationEndpoint, [id]),
            ),
          )
          as String);

  @override
  String getNotificationEndpoint() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationEndpoint, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getNotificationEndpoint, []),
            ),
          )
          as String);

  @override
  String getPeakPlateEndpoint(String? city, String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#getPeakPlateEndpoint, [city, plate]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getPeakPlateEndpoint, [city, plate]),
            ),
          )
          as String);

  @override
  String getReloadExpirationEndpoint(
    String? name, {
    int? expirationId,
    int? vehicleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getReloadExpirationEndpoint,
              [name],
              {#expirationId: expirationId, #vehicleId: vehicleId},
            ),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(
                #getReloadExpirationEndpoint,
                [name],
                {#expirationId: expirationId, #vehicleId: vehicleId},
              ),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> reloadExpiration(
    String? name, {
    String? token,
    int? expirationId,
    int? vehicleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reloadExpiration,
              [name],
              {
                #token: token,
                #expirationId: expirationId,
                #vehicleId: vehicleId,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> queryHistory({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#queryHistory, [], {#token: token}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getUserProfileEndpoint(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileEndpoint, [userId]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getUserProfileEndpoint, [userId]),
            ),
          )
          as String);

  @override
  String updateUserProfileEndpoint(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileEndpoint, [userId]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#updateUserProfileEndpoint, [userId]),
            ),
          )
          as String);

  @override
  String updateUserPhotoEndpoint() =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPhotoEndpoint, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#updateUserPhotoEndpoint, []),
            ),
          )
          as String);

  @override
  String updateUserPasswordEndpoint() =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPasswordEndpoint, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#updateUserPasswordEndpoint, []),
            ),
          )
          as String);

  @override
  String deleteUserAccountEndpoint(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAccountEndpoint, [userId]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deleteUserAccountEndpoint, [userId]),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {#queryParams: queryParams, #token: token},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint], {#body: body, #token: token}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint], {#body: body, #token: token}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> delete(String? endpoint, {String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint], {#token: token}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [endpoint], {#body: body, #token: token}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> patchWithFile(
    String? endpoint, {
    required _i5.File? file,
    Map<String, String>? fields,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchWithFile,
              [endpoint],
              {#file: file, #fields: fields, #token: token},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthContext extends _i1.Mock implements _i6.AuthContext {
  MockAuthContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setUserData({
    required String? token,
    required String? name,
    required String? phone,
    String? photo,
    int? userId,
  }) => super.noSuchMethod(
    Invocation.method(#setUserData, [], {
      #token: token,
      #name: name,
      #phone: phone,
      #photo: photo,
      #userId: userId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updatePhoto(String? photoUrl) => super.noSuchMethod(
    Invocation.method(#updatePhoto, [photoUrl]),
    returnValueForMissingStub: null,
  );

  @override
  void updateName(String? name) => super.noSuchMethod(
    Invocation.method(#updateName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
